#!/bin/bash
echo "Welcome to  Whiteboard!"
A simple whiteboard application for linux and windows platform.
This was a simple project for Operating System course instructed by Ms. Aliza Ahmed Khan

Created by Mehedi Hasan Hridoy & Umme Salma Lamyea
Visit: https://github.com//mehedi-hridoy for more projects

